apiVersion: v1
kind: Service
metadata:
  name: backend-cluster-ip-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: backend
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
